"""Make phone optional and add alternative contact fields

Revision ID: 19b3cef14e82
Revises: 2c69ba98de99
Create Date: 2026-02-22 00:16:43.499952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b3cef14e82'
down_revision = '2c69ba98de99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(length=20), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.create_unique_constraint("uq_member_id_number", ['id_number'])

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('alternative_contact')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint("uq_member_id_number", type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('id_number')
        batch_op.drop_column('alternative_contact')

    # ### end Alembic commands ###
