"""initial

Revision ID: 2c69ba98de99
Revises: 
Create Date: 2026-02-20 02:48:52.517754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c69ba98de99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='uq_lookup_category_value')
    )
    with op.batch_alter_table('lookup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lookup_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_lookup_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_lookup_value'), ['value'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'day_of_week', 'time', name='unique_service_per_day_time')
    )
    op.create_table('sms_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_type', 'message', name='uq_sms_type_message')
    )
    op.create_table('document_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_doc_category_branch_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('membership_course', sa.Boolean(), nullable=True),
    sa.Column('baptized', sa.Boolean(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('member_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_birthday_sms_year', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_member_branch_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_phone'), ['phone'], unique=False)

    op.create_table('sms_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('related_table', sa.String(length=50), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_sms_logs_branch_id'),
    sa.ForeignKeyConstraint(['template_id'], ['sms_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_logs_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_logs_status'), ['status'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_user_branch_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_visitor_branch_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_phone'), ['phone'], unique=True)

    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', 'service_id', 'check_in_date', name='unique_checkin_per_service_per_day')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.String(length=50), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_document_branch_id'),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], name='fk_document_category_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giving',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('giving_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_giving_branch_id'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('giving', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giving_giving_type'), ['giving_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_giving_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('giving', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giving_phone'))
        batch_op.drop_index(batch_op.f('ix_giving_giving_type'))

    op.drop_table('giving')
    op.drop_table('document')
    op.drop_table('check_in')
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_phone'))

    op.drop_table('visitor')
    op.drop_table('user')
    with op.batch_alter_table('sms_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_logs_status'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_phone'))
        batch_op.drop_index(batch_op.f('ix_sms_logs_message_type'))

    op.drop_table('sms_logs')
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_phone'))

    op.drop_table('member')
    op.drop_table('inventory_item')
    op.drop_table('document_categories')
    op.drop_table('sms_templates')
    op.drop_table('services')
    with op.batch_alter_table('lookup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lookup_value'))
        batch_op.drop_index(batch_op.f('ix_lookup_is_active'))
        batch_op.drop_index(batch_op.f('ix_lookup_category'))

    op.drop_table('lookup')
    op.drop_table('events')
    op.drop_table('department')
    op.drop_table('branches')
    # ### end Alembic commands ###
