"""Add giver_name to giving

Revision ID: 3080f93fe000
Revises: 6e1c53db654d
Create Date: 2026-02-23 19:15:23.896398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3080f93fe000'
down_revision = '6e1c53db654d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
