"""add sermons table

Revision ID: 9931336a25e5
Revises: c1da9b7ed906
Create Date: 2026-03-23 16:39:56.467599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9931336a25e5'
down_revision = 'c1da9b7ed906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sermons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('pastor_name', sa.String(length=100), nullable=False),
    sa.Column('sermon_date', sa.Date(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='fk_sermon_branch_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sermons_branch_id'), ['branch_id'], unique=False)

    op.drop_table('department')
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_inventory_item_branch_id'), ['branch_id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'lookup', ['department_id'], ['id'])

    with op.batch_alter_table('stock_responsible_person', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_responsible_person', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_inventory_item_branch_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('department',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sermons_branch_id'))

    op.drop_table('sermons')
    # ### end Alembic commands ###
