"""Add document category hierarchy

Revision ID: a66f43581de2
Revises: d5d69dfd0608
Create Date: 2026-03-24 22:33:32.506817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66f43581de2'
down_revision = 'd5d69dfd0608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_doc_category_parent_id', 'document_categories', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_doc_category_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
